name = "Wacky Winter Wonderland"
author = "EnderLord0042"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93a974fa329c9d846d81624c767b6b6df61bfe831dca1299c68d574bc4c5f40c"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
