name = "Wacky Winter Wonderland"
author = "EnderLord0042"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b30ca94ac2533ebb6ce934175ff4101befc6eafea8de89b878748bf70153765"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
