name = "Wacky Winter Wonderland"
author = "EnderLord0042"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "70de86569a3a39efe9e0ffc057a1c91b38d7a28d1fe3aab7e012e720a43fefc6"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
