name = "Wacky Winter Wonderland"
author = "EnderLord0042"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "85a52572292114e00743c7dffa8887c0c6aadf5c0538e507651d6f4d3019ac20"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
