name = "Wacky Winter Wonderland"
author = "EnderLord0042"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "712a894f18cbd5fd8c6b3fcde49f4b324aaf0179544c345121fee7408113a762"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
